#!/usr/bin/expect
set USER   [lindex $argv 0]
set IP     [lindex $argv 1]
set PASSWD [lindex $argv 2]
set CMD [lindex $argv 3]
set timeout 18000

spawn ssh $USER@$IP $CMD
expect {
"(yes/no)?" { send "yes\r" ;exp_continue }
"assword:" { send "$PASSWD\r" }
}
#expect eof
